# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: echo "KEY ID > ${{ secrets.AWS_ACCESS_KEY_ID }}"
    - name: Serverless
      uses: serverless/github-action@v3
      with: 
        args: deploy
      env: 
        AWS_ACCESS_KEY_ID: "AKIA2BEKRBHN67JV2KRN"
        AWS_SECRET_ACCESS_KEY: "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"
 
